token : #Put in this account token
channel_to_dep : # channel for this account to run commands in
main_account_channel : # This is where your main account token would be, for automatic money transfer
log_channel : # This is where u wanna see some Logs of what the bot did
