token : #Token of your alt
channel_to_dep : #text channel to run ur alt
main_account_channel : # Main account channel
log_channel : # any channel to log
# Note: all 3 channels can be the same, if it's the token of your main account.
